import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { PGlite } from "@electric-sql/pglite";

const adminCatalogueMigration = await readFile(
  new URL("../migrations/20260926120000_admin_catalogue_v1.sql", import.meta.url),
  "utf8"
);
const occurrenceIdentityMigration = await readFile(
  new URL("../migrations/20260927120000_album_track_occurrence_identity.sql", import.meta.url),
  "utf8"
);
const reconciliationMigration = await readFile(
  new URL("../migrations/20260929120000_admin_catalogue_album_reconciliation.sql", import.meta.url),
  "utf8"
);
const ADMIN_ID = "11111111-1111-4111-8111-111111111111";
const MEMBER_ID = "22222222-2222-4222-8222-222222222222";
const RELEASE_ID = "33333333-3333-4333-8333-333333333333";
const GROUP_ID = "44444444-4444-4444-8444-444444444444";
const RECORDING_ID = "55555555-5555-4555-8555-555555555555";

async function fixture({ applyOccurrenceIdentity = true } = {}) {
  const db = new PGlite();
  await db.exec(`
    create role anon;
    create role authenticated;
    create role service_role;
    create schema auth;
    create function auth.uid() returns uuid language sql stable
      as 'select nullif(current_setting(''request.jwt.claim.sub'', true), '''')::uuid';
    create table public.profiles (id uuid primary key, is_admin boolean not null default false);
    create table public.albums (
      id bigint generated by default as identity primary key,
      title text not null, artist text not null, created_at timestamptz default now(),
      external_source text, external_id text, cover_art_url text, release_date date,
      custom_cover text, is_deleted boolean default false,
      musicbrainz_release_group_id text, musicbrainz_release_id text,
      original_release_date date, canonical_release_date date,
      canonical_release_country text, catalogue_selection_version integer
    );
    create unique index albums_external_source_external_id_unique on public.albums(external_source,external_id);
    create unique index albums_title_artist_unique on public.albums(title,artist);
    create unique index albums_musicbrainz_release_group_unique on public.albums(musicbrainz_release_group_id)
      where musicbrainz_release_group_id is not null and is_deleted is not true;
    create table public.songs (
      id bigint generated by default as identity primary key,
      title text not null, artist text not null, album_id bigint references public.albums(id) on delete set null,
      external_source text, external_id text, created_at timestamptz default now(),
      is_deleted boolean default false, canonical_song_id uuid, track_position integer, canonical_song_key text
    );
    create unique index songs_external_source_external_id_unique on public.songs(external_source,external_id);
    create unique index songs_external_unique on public.songs(external_source,external_id)
      where external_source is not null and external_id is not null;
    create unique index songs_unique_track on public.songs(album_id,lower(title));
    create table public.song_ratings(
      id bigint generated by default as identity primary key,
      user_id uuid not null,
      song_id bigint not null references public.songs(id) on delete cascade,
      rating numeric not null,
      unique(user_id,song_id)
    );
    create table public.tracked_artists(id bigint generated by default as identity primary key, artist_name text unique);
    create function public.sync_tracked_artist_from_album() returns trigger language plpgsql as $$
      begin insert into public.tracked_artists(artist_name) values(new.artist) on conflict do nothing; return new; end $$;
    create trigger trg_sync_tracked_artist_from_album after insert on public.albums
      for each row execute function public.sync_tracked_artist_from_album();
    create table public.catalogue_worker_state(
      singleton boolean primary key default true,
      next_musicbrainz_at timestamptz,
      constraint singleton_true check(singleton)
    );
    insert into profiles(id,is_admin) values ('${ADMIN_ID}',true),('${MEMBER_ID}',false);
    grant usage on schema public,auth to anon,authenticated,service_role;
    grant select on public.profiles to authenticated;
    grant select,insert,update,delete on public.albums,public.songs to authenticated;
    grant usage,select on sequence public.albums_id_seq,public.songs_id_seq to authenticated;
    grant all on public.catalogue_worker_state to service_role;
    create policy "Logged in users can insert albums" on public.albums for insert to authenticated with check(auth.uid() is not null);
    create policy "Logged in users can insert songs" on public.songs for insert to authenticated with check(auth.uid() is not null);
    alter table public.albums enable row level security;
    alter table public.songs enable row level security;
    create policy "read albums" on public.albums for select using(true);
    create policy "read songs" on public.songs for select using(true);
    create policy "Admins can do anything on albums" on public.albums to authenticated
      using(exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_admin))
      with check(exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_admin));
    create policy "Admins can do anything on songs" on public.songs to authenticated
      using(exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_admin))
      with check(exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_admin));
  `);
  await db.exec(adminCatalogueMigration);
  if (applyOccurrenceIdentity) await db.exec(occurrenceIdentityMigration);
  if (applyOccurrenceIdentity) await db.exec(reconciliationMigration);
  return db;
}

const album = {
  title: "First Album", artist: "The Example",
  musicbrainz_release_id: RELEASE_ID,
  musicbrainz_release_group_id: GROUP_ID,
  cover_art_url: `https://coverartarchive.org/release-group/${GROUP_ID}/front-250`,
  uk_release_date: "1984-02-20", original_release_date: "1984-02-20",
  canonical_release_date: "1984-02-20", canonical_release_country: "GB"
};
const tracks = [{ position: 1, title: "Opening Track", artist: "The Example", musicbrainz_recording_id: RECORDING_ID }];

async function asUser(db, userId, sql, params = []) {
  await db.exec(`set role authenticated; set "request.jwt.claim.sub"='${userId}'`);
  try { return await db.query(sql, params); }
  finally { await db.exec('reset role; reset "request.jwt.claim.sub"'); }
}

async function add(db, userId = ADMIN_ID, requestedAlbum = album, requestedTracks = tracks) {
  return asUser(db, userId,
    "select admin_add_catalogue_album($1::jsonb,$2::jsonb) result",
    [JSON.stringify(requestedAlbum), JSON.stringify(requestedTracks)]);
}

async function reconcile(db, userId, albumId, requestedAlbum, requestedTracks) {
  return asUser(db, userId,
    "select admin_reconcile_catalogue_album($1,$2::jsonb,$3::jsonb) result",
    [albumId, JSON.stringify({ id: albumId, ...requestedAlbum }), JSON.stringify(requestedTracks)]);
}

test("incomplete albums reconcile atomically while retaining matching song IDs and ratings", async () => {
  const db = await fixture();
  try {
    await db.exec(`insert into albums(id,title,artist,external_source,external_id)
      values(283,'First Album','The Example','musicbrainz','${RELEASE_ID}');
      insert into songs(id,title,artist,album_id,external_source,external_id,track_position)
      values(16789,'Opening Track','The Example',283,'musicbrainz','${RECORDING_ID}',null);
      insert into song_ratings(user_id,song_id,rating) values('${MEMBER_ID}',16789,9);`);
    const completeTracks = [tracks[0], {
      position: 2, title: "Second Track", artist: "The Example",
      musicbrainz_recording_id: "66666666-6666-4666-8666-666666666666"
    }];
    const result = (await reconcile(db, ADMIN_ID, 283, album, completeTracks)).rows[0].result;
    assert.equal(result.status, "reconciled");
    assert.equal(result.retained_count, 1);
    assert.equal(result.inserted_count, 1);
    const savedAlbum = (await db.query("select * from albums where id=283")).rows[0];
    assert.equal(savedAlbum.musicbrainz_release_id, RELEASE_ID);
    assert.equal(savedAlbum.musicbrainz_release_group_id, GROUP_ID);
    const savedSongs = (await db.query("select id,track_position from songs where album_id=283 order by track_position")).rows;
    assert.equal(Number(savedSongs[0].id), 16789);
    assert.equal(savedSongs[0].track_position, 1);
    assert.notEqual(Number(savedSongs[1].id), 16789);
    assert.equal(savedSongs[1].track_position, 2);
    assert.equal(Number((await db.query("select song_id from song_ratings")).rows[0].song_id), 16789);

    const again = (await reconcile(db, ADMIN_ID, 283, album, completeTracks)).rows[0].result;
    assert.equal(again.status, "unchanged");
    assert.equal(again.inserted_count, 0);
    assert.equal((await db.query("select count(*)::int n from songs where album_id=283")).rows[0].n, 2);
  } finally { await db.close(); }
});

test("reconciliation conflicts roll back provenance, positions and inserts", async () => {
  const db = await fixture();
  try {
    await db.exec(`insert into albums(id,title,artist,external_source,external_id)
      values(283,'First Album','The Example','musicbrainz','${RELEASE_ID}');
      insert into songs(id,title,artist,album_id,external_source,external_id,track_position)
      values(16789,'Unrelated','The Example',283,'musicbrainz','77777777-7777-4777-8777-777777777777',7);`);
    await assert.rejects(reconcile(db, ADMIN_ID, 283, album, tracks), /conflict/i);
    const savedAlbum = (await db.query("select * from albums where id=283")).rows[0];
    const savedSong = (await db.query("select * from songs where id=16789")).rows[0];
    assert.equal(savedAlbum.musicbrainz_release_id, null);
    assert.equal(savedSong.track_position, 7);
    assert.equal((await db.query("select count(*)::int n from songs where album_id=283")).rows[0].n, 1);
  } finally { await db.close(); }
});

test("ordinary users cannot invoke catalogue reconciliation", async () => {
  const db = await fixture();
  try {
    await db.exec(`insert into albums(id,title,artist,external_source,external_id)
      values(283,'First Album','The Example','musicbrainz','${RELEASE_ID}')`);
    await assert.rejects(reconcile(db, MEMBER_ID, 283, album, tracks), /Admin access required/);
    assert.equal((await db.query("select count(*)::int n from songs where album_id=283")).rows[0].n, 0);
  } finally { await db.close(); }
});

test("complete existing albums remain unchanged", async () => {
  const db = await fixture();
  try {
    await db.exec(`insert into albums(id,title,artist,external_source,external_id,musicbrainz_release_id,musicbrainz_release_group_id)
      values(283,'First Album','The Example','musicbrainz','${RELEASE_ID}','${RELEASE_ID}','${GROUP_ID}');
      insert into songs(id,title,artist,album_id,external_source,external_id,track_position)
      values(16789,'Opening Track','The Example',283,'musicbrainz','${RECORDING_ID}',1);`);
    const result = (await reconcile(db, ADMIN_ID, 283, album, tracks)).rows[0].result;
    assert.equal(result.status, "unchanged");
    assert.equal(result.retained_count, 1);
    assert.equal(result.inserted_count, 0);
  } finally { await db.close(); }
});

test("migration closes member inserts and removes automatic tracked-artist creation", async () => {
  const db = await fixture();
  try {
    const policies = await db.query(`select policyname from pg_policies where schemaname='public'
      and policyname in ('Logged in users can insert albums','Logged in users can insert songs')`);
    assert.equal(policies.rows.length, 0);
    const trigger = await db.query("select 1 from pg_trigger where tgname='trg_sync_tracked_artist_from_album'");
    assert.equal(trigger.rows.length, 0);
    await assert.rejects(
      asUser(db, MEMBER_ID, "insert into albums(title,artist) values('No','Member')"),
      /row-level security|policy/i
    );
  } finally { await db.close(); }
});

test("admin RPC atomically adds canonical album provenance and tracks", async () => {
  const db = await fixture();
  try {
    const response = (await add(db)).rows[0].result;
    assert.equal(response.status, "added");
    assert.equal(response.track_count, 1);
    const saved = (await db.query("select * from albums")).rows[0];
    assert.equal(saved.musicbrainz_release_group_id, GROUP_ID);
    assert.equal(saved.release_date.toISOString().slice(0,10), "1984-02-20");
    assert.equal(saved.canonical_release_country, "GB");
    const savedTrack = (await db.query("select * from songs")).rows[0];
    assert.equal(savedTrack.album_id, saved.id);
    assert.equal(savedTrack.external_id, RECORDING_ID);
    assert.equal((await db.query("select count(*)::int n from tracked_artists")).rows[0].n, 0);
  } finally { await db.close(); }
});

test("non-admin RPC calls fail before any catalogue write", async () => {
  const db = await fixture();
  try {
    await assert.rejects(add(db, MEMBER_ID), /Admin access required/);
    assert.equal((await db.query("select count(*)::int n from albums")).rows[0].n, 0);
    assert.equal((await db.query("select count(*)::int n from songs")).rows[0].n, 0);
  } finally { await db.close(); }
});

test("duplicate release groups return Already exists without adding tracks", async () => {
  const db = await fixture();
  try {
    assert.equal((await add(db)).rows[0].result.status, "added");
    const duplicate = (await add(db, ADMIN_ID, { ...album, musicbrainz_release_id: "77777777-7777-4777-8777-777777777777" }, [
      { ...tracks[0], musicbrainz_recording_id: "88888888-8888-4888-8888-888888888888" }
    ])).rows[0].result;
    assert.equal(duplicate.status, "already_exists");
    assert.equal((await db.query("select count(*)::int n from albums")).rows[0].n, 1);
    assert.equal((await db.query("select count(*)::int n from songs")).rows[0].n, 1);
  } finally { await db.close(); }
});

test("the same recording can be added as a distinct occurrence on another album", async () => {
  const db = await fixture();
  try {
    await db.exec(`insert into albums(title,artist) values('Other','The Example');
      insert into songs(title,artist,album_id,external_source,external_id,track_position)
      values('Opening Track','The Example',1,'musicbrainz','${RECORDING_ID}',1)`);
    const response = (await add(db, ADMIN_ID, { ...album, title: "New Album" })).rows[0].result;
    assert.equal(response.status, "added");
    const occurrences = await db.query(
      "select id,album_id from songs where external_source='musicbrainz' and external_id=$1 order by id",
      [RECORDING_ID]
    );
    assert.equal(occurrences.rows.length, 2);
    assert.notEqual(occurrences.rows[0].id, occurrences.rows[1].id);
    assert.notEqual(occurrences.rows[0].album_id, occurrences.rows[1].album_id);
  } finally { await db.close(); }
});

test("album-scoped constraints reject duplicate recording and track position", async () => {
  const db = await fixture();
  try {
    await db.exec(`insert into albums(title,artist) values('Slots','The Example');
      insert into songs(title,artist,album_id,external_source,external_id,track_position)
      values('First','The Example',1,'musicbrainz','${RECORDING_ID}',1)`);
    await assert.rejects(
      db.exec(`insert into songs(title,artist,album_id,external_source,external_id,track_position)
        values('Same recording','The Example',1,'musicbrainz','${RECORDING_ID}',2)`),
      /unique|duplicate/i
    );
    await assert.rejects(
      db.exec(`insert into songs(title,artist,album_id,external_source,external_id,track_position)
        values('Same slot','The Example',1,'musicbrainz','66666666-6666-4666-8666-666666666666',1)`),
      /unique|duplicate/i
    );
  } finally { await db.close(); }
});

test("occurrence migration refuses duplicate album track positions without rewriting data", async () => {
  const db = await fixture({ applyOccurrenceIdentity: false });
  try {
    await db.exec(`insert into albums(title,artist) values('Broken slots','The Example');
      insert into songs(title,artist,album_id,external_source,external_id,track_position) values
        ('First','The Example',1,'manual','one',1),
        ('Second','The Example',1,'manual','two',1)`);
    await assert.rejects(db.exec(occurrenceIdentityMigration), /duplicate album track positions/i);
  } finally { await db.close(); }
});

test("occurrence migration refuses duplicate recording identity within one album", async () => {
  const db = await fixture({ applyOccurrenceIdentity: false });
  try {
    await db.exec(`drop index songs_external_source_external_id_unique; drop index songs_external_unique;
      insert into albums(title,artist) values('Broken recordings','The Example');
      insert into songs(title,artist,album_id,external_source,external_id,track_position) values
        ('First','The Example',1,'musicbrainz','${RECORDING_ID}',1),
        ('Second','The Example',1,'musicbrainz','${RECORDING_ID}',2)`);
    await assert.rejects(db.exec(occurrenceIdentityMigration), /duplicate recording identities exist within an album/i);
  } finally { await db.close(); }
});

test("Hatful regression preserves the existing occurrence and its rating", async () => {
  const db = await fixture();
  try {
    const sharedRecording = "cae8bbec-c2ff-4972-9218-8f90acb07b1b";
    await db.exec(`
      insert into albums(title,artist,external_source,external_id,musicbrainz_release_id,musicbrainz_release_group_id)
      values('Meat Is Murder','The Smiths','musicbrainz','5c7b0f8a-2bfb-45bc-b0a2-249870921e46',
        '5c7b0f8a-2bfb-45bc-b0a2-249870921e46','0d56f03e-0e50-3de4-b2c4-193ab405e779');
      insert into songs(id,title,artist,album_id,external_source,external_id,track_position)
      values(6665,'How Soon Is Now?','The Smiths',1,'musicbrainz','${sharedRecording}',6);
      insert into song_ratings(user_id,song_id,rating) values('${MEMBER_ID}',6665,9);
    `);
    const recordingIds = [
      "218f0f63-2d0d-4819-be71-ae548c8b2cd2", "ac15853b-90a0-4922-b5c3-448bc6e16665",
      "82bb27ee-67b0-4f68-969b-6469450093b1", "4cb75bdb-7ecb-4148-bb2e-2a28a05c9582",
      sharedRecording, "cf5c0e4a-b689-4852-b562-ca6a2d67e8dc", "279cfaed-f5fb-465e-b266-ecf896b7fb1b",
      "31745644-7e0d-4061-952d-3cee2aaf0931", "69cabdb6-0909-4177-b41d-6f39e75c250b",
      "b48b3046-0feb-45ba-83f3-741f6be22b18", "542f5a7e-85d6-40f9-99c0-695d1f5283cb",
      "af40a07c-8b61-4ea9-9ae6-1a188f34ef1b", "725ff6ce-094f-433f-88b7-c53c3cf86301",
      "bf8a0ec2-68b4-4bb1-a07e-37ee55deaf85", "8104704e-c28f-42c6-8845-a96f09d93c24",
      "8bfcdf04-af90-4a12-adfd-73a5d38b47ba"
    ];
    const titles = ["William, It Was Really Nothing", "What Difference Does It Make?", "These Things Take Time",
      "This Charming Man", "How Soon Is Now?", "Handsome Devil", "Hand in Glove", "Still Ill",
      "Heaven Knows I'm Miserable Now", "This Night Has Opened My Eyes", "You've Got Everything Now",
      "Accept Yourself", "Girl Afraid", "Back to the Old House", "Reel Around the Fountain",
      "Please Please Please Let Me Get What I Want"];
    const hatfulTracks = recordingIds.map((id, index) => ({
      position: index + 1, title: titles[index], artist: "The Smiths", musicbrainz_recording_id: id
    }));
    const result = (await add(db, ADMIN_ID, {
      title: "Hatful of Hollow", artist: "The Smiths",
      musicbrainz_release_id: "241680ca-ffc6-4106-8d63-a9c7dbdc5925",
      musicbrainz_release_group_id: "f81500a3-d01a-30e7-8ec9-75f672e9a775",
      uk_release_date: "1984-11-12", canonical_release_date: "1984-11-12", canonical_release_country: "GB"
    }, hatfulTracks)).rows[0].result;
    assert.equal(result.status, "added");
    assert.equal(result.track_count, 16);
    assert.equal((await db.query("select count(*)::int n from albums")).rows[0].n, 2);
    assert.equal((await db.query("select count(*)::int n from songs")).rows[0].n, 17);
    const shared = await db.query("select id,album_id,track_position from songs where external_id=$1 order by id", [sharedRecording]);
    assert.equal(shared.rows.length, 2);
    const meatOccurrence = shared.rows.find((row) => row.id === 6665);
    const hatfulOccurrence = shared.rows.find((row) => row.id !== 6665);
    assert.equal(meatOccurrence.album_id, 1);
    assert.equal(meatOccurrence.track_position, 6);
    assert.ok(hatfulOccurrence.id);
    assert.notEqual(hatfulOccurrence.album_id, 1);
    assert.equal(hatfulOccurrence.track_position, 5);
    const ratings = await db.query("select user_id,song_id,rating from song_ratings");
    assert.equal(ratings.rows.length, 1);
    assert.equal(ratings.rows[0].user_id, MEMBER_ID);
    assert.equal(ratings.rows[0].song_id, 6665);
    assert.equal(Number(ratings.rows[0].rating), 9);
  } finally { await db.close(); }
});

test("an invalid track rolls back the whole album", async () => {
  const db = await fixture();
  try {
    await assert.rejects(add(db, ADMIN_ID, album, [{ ...tracks[0], musicbrainz_recording_id: "not-a-uuid" }]),
      /Every track requires/);
    assert.equal((await db.query("select count(*)::int n from albums")).rows[0].n, 0);
    assert.equal((await db.query("select count(*)::int n from songs")).rows[0].n, 0);
  } finally { await db.close(); }
});

test("a track insertion failure rolls back the album and earlier tracks", async () => {
  const db = await fixture();
  try {
    await db.exec("alter table songs add constraint reject_test_track check (title <> 'Explode')");
    await assert.rejects(add(db, ADMIN_ID, album, [
      tracks[0],
      { position: 2, title: "Explode", artist: "The Example", musicbrainz_recording_id: "99999999-9999-4999-8999-999999999999" }
    ]), /reject_test_track|check constraint/i);
    assert.equal((await db.query("select count(*)::int n from albums")).rows[0].n, 0);
    assert.equal((await db.query("select count(*)::int n from songs")).rows[0].n, 0);
  } finally { await db.close(); }
});

test("concurrent duplicate submissions remain idempotent", async () => {
  const db = await fixture();
  try {
    await db.exec(`set role authenticated; set "request.jwt.claim.sub"='${ADMIN_ID}'`);
    const [first, second] = await Promise.all([
      db.query("select admin_add_catalogue_album($1::jsonb,$2::jsonb) result", [JSON.stringify(album), JSON.stringify(tracks)]),
      db.query("select admin_add_catalogue_album($1::jsonb,$2::jsonb) result", [JSON.stringify(album), JSON.stringify(tracks)])
    ]);
    await db.exec('reset role; reset "request.jwt.claim.sub"');
    assert.deepEqual([first.rows[0].result.status, second.rows[0].result.status].sort(), ["added", "already_exists"]);
    assert.equal((await db.query("select count(*)::int n from albums")).rows[0].n, 1);
    assert.equal((await db.query("select count(*)::int n from songs")).rows[0].n, 1);
  } finally { await db.close(); }
});

test("MusicBrainz slots are shared without touching importer queue data", async () => {
  const db = await fixture();
  try {
    await db.exec("set role service_role");
    const first = (await db.query("select admin_catalogue_musicbrainz_slot() wait_ms")).rows[0].wait_ms;
    const second = (await db.query("select admin_catalogue_musicbrainz_slot() wait_ms")).rows[0].wait_ms;
    await db.exec("reset role");
    assert.equal(first, 0);
    assert.ok(second > 0);
  } finally { await db.close(); }
});
