import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { PGlite } from "@electric-sql/pglite";

const migration = await readFile(
  new URL("../migrations/20260927160832_admin_catalogue_delete_album.sql", import.meta.url),
  "utf8"
);
const ADMIN_ID = "11111111-1111-4111-8111-111111111111";
const MEMBER_ID = "22222222-2222-4222-8222-222222222222";
const RATER_ID = "33333333-3333-4333-8333-333333333333";
const RECORDING_ID = "cae8bbec-c2ff-4972-9218-8f90acb07b1b";

async function fixture() {
  const db = new PGlite();
  await db.exec(`
    create role anon;
    create role authenticated;
    create schema auth;
    create function auth.uid() returns uuid language sql stable
      as 'select nullif(current_setting(''request.jwt.claim.sub'', true), '''')::uuid';
    create table public.profiles(id uuid primary key, is_admin boolean not null default false);
    create table public.albums(
      id bigint generated by default as identity primary key,
      artist text not null, title text not null, is_deleted boolean not null default false
    );
    create table public.songs(
      id bigint generated by default as identity primary key,
      album_id bigint references public.albums(id) on delete set null,
      artist text not null, title text not null, track_position integer,
      external_source text, external_id text, is_deleted boolean not null default false
    );
    create table public.ratings(
      id bigint generated by default as identity primary key,
      user_id uuid not null, album_id bigint not null references public.albums(id) on delete cascade,
      rating numeric not null
    );
    create table public.song_ratings(
      id bigint generated by default as identity primary key,
      user_id uuid not null, song_id bigint not null references public.songs(id) on delete cascade,
      rating numeric not null
    );
    create table public.album_reviews(
      id uuid primary key, user_id uuid not null,
      album_id bigint not null references public.albums(id) on delete cascade,
      review_text text not null
    );
    create table public.album_review_comments(
      id uuid primary key, review_id uuid not null references public.album_reviews(id) on delete cascade,
      user_id uuid not null, comment_text text not null
    );
    create table public.album_review_likes(
      review_id uuid not null references public.album_reviews(id) on delete cascade,
      user_id uuid not null, primary key(review_id,user_id)
    );
    insert into profiles(id,is_admin) values ('${ADMIN_ID}',true),('${MEMBER_ID}',false);
    grant usage on schema public,auth to authenticated;
    grant select on public.profiles,public.ratings,public.song_ratings,public.album_reviews,
      public.album_review_comments,public.album_review_likes to authenticated;
    grant select,update,delete on public.albums,public.songs to authenticated;
    alter table public.albums enable row level security;
    alter table public.songs enable row level security;
    create policy admin_albums on public.albums to authenticated
      using(exists(select 1 from profiles where id=auth.uid() and is_admin))
      with check(exists(select 1 from profiles where id=auth.uid() and is_admin));
    create policy admin_songs on public.songs to authenticated
      using(exists(select 1 from profiles where id=auth.uid() and is_admin))
      with check(exists(select 1 from profiles where id=auth.uid() and is_admin));
  `);
  await db.exec(migration);
  return db;
}

async function asUser(db, userId, albumId, execute = true) {
  await db.exec(`set role authenticated; set "request.jwt.claim.sub"='${userId}'`);
  try {
    return await db.query(
      "select public.admin_catalogue_delete_album($1::bigint,$2::boolean) result",
      [albumId, execute]
    );
  } finally {
    await db.exec('reset role; reset "request.jwt.claim.sub"');
  }
}

test("unrated album is hard-deleted with only its own track occurrences", async () => {
  const db = await fixture();
  try {
    await db.exec(`
      insert into albums(artist,title) values ('The Smiths','Unwanted'),('The Smiths','Meat Is Murder');
      insert into songs(album_id,artist,title,track_position,external_source,external_id) values
        (1,'The Smiths','How Soon Is Now?',1,'musicbrainz','${RECORDING_ID}'),
        (2,'The Smiths','How Soon Is Now?',6,'musicbrainz','${RECORDING_ID}');
      insert into song_ratings(user_id,song_id,rating) values ('${RATER_ID}',2,9);
    `);
    const result = (await asUser(db, ADMIN_ID, 1)).rows[0].result;
    assert.equal(result.status, "deleted");
    assert.equal((await db.query("select count(*)::int n from albums where id=1")).rows[0].n, 0);
    assert.equal((await db.query("select count(*)::int n from songs where album_id=1")).rows[0].n, 0);
    assert.deepEqual((await db.query("select id,album_id,external_id from songs")).rows,
      [{ id: 2, album_id: 2, external_id: RECORDING_ID }]);
    assert.equal((await db.query("select song_id,rating from song_ratings")).rows[0].song_id, 2);
  } finally { await db.close(); }
});

test("album with user data is hidden and all user rows are preserved", async () => {
  const db = await fixture();
  try {
    await db.exec(`
      insert into albums(artist,title) values ('The Smiths','Rated');
      insert into songs(album_id,artist,title,track_position) values (1,'The Smiths','A Song',1);
      insert into ratings(user_id,album_id,rating) values ('${RATER_ID}',1,8);
      insert into song_ratings(user_id,song_id,rating) values ('${RATER_ID}',1,7);
      insert into album_reviews(id,user_id,album_id,review_text)
        values ('44444444-4444-4444-8444-444444444444','${RATER_ID}',1,'Review');
      insert into album_review_comments(id,review_id,user_id,comment_text)
        values ('55555555-5555-4555-8555-555555555555','44444444-4444-4444-8444-444444444444','${RATER_ID}','Comment');
      insert into album_review_likes(review_id,user_id)
        values ('44444444-4444-4444-8444-444444444444','${RATER_ID}');
    `);
    const preview = (await asUser(db, ADMIN_ID, 1, false)).rows[0].result;
    assert.equal(preview.deletion_mode, "hide");
    assert.equal(preview.album_rating_count, 1);
    assert.equal(preview.album_review_count, 1);
    assert.equal(preview.track_rating_count, 1);
    const result = (await asUser(db, ADMIN_ID, 1)).rows[0].result;
    assert.equal(result.status, "hidden");
    assert.equal((await db.query("select is_deleted from albums where id=1")).rows[0].is_deleted, true);
    assert.equal((await db.query("select is_deleted from songs where id=1")).rows[0].is_deleted, true);
    for (const table of ["ratings", "song_ratings", "album_reviews", "album_review_comments", "album_review_likes"]) {
      assert.equal((await db.query(`select count(*)::int n from ${table}`)).rows[0].n, 1);
    }
  } finally { await db.close(); }
});

test("non-admin, invalid and nonexistent album requests fail without writes", async () => {
  const db = await fixture();
  try {
    await db.exec("insert into albums(artist,title) values ('Artist','Album')");
    await assert.rejects(asUser(db, MEMBER_ID, 1), /Admin access required/);
    await assert.rejects(asUser(db, ADMIN_ID, 0), /Invalid album ID/);
    await assert.rejects(asUser(db, ADMIN_ID, 999), /Album not found/);
    assert.equal((await db.query("select count(*)::int n from albums")).rows[0].n, 1);
  } finally { await db.close(); }
});

test("a failure after track deletion rolls the entire transaction back", async () => {
  const db = await fixture();
  try {
    await db.exec(`
      insert into albums(artist,title) values ('Artist','Protected');
      insert into songs(album_id,artist,title,track_position) values (1,'Artist','Track',1);
      create function reject_album_delete() returns trigger language plpgsql as $$
        begin raise exception 'forced deletion failure'; end $$;
      create trigger reject_album_delete before delete on albums
        for each row execute function reject_album_delete();
    `);
    await assert.rejects(asUser(db, ADMIN_ID, 1), /forced deletion failure/);
    assert.equal((await db.query("select count(*)::int n from albums where id=1")).rows[0].n, 1);
    assert.equal((await db.query("select count(*)::int n from songs where album_id=1")).rows[0].n, 1);
  } finally { await db.close(); }
});
