import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { test } from "node:test";
import { PGlite } from "@electric-sql/pglite";

const migration = await readFile(
  new URL("../migrations/20260920133904_admin_album_track_listing_editor.sql", import.meta.url),
  "utf8"
);

const ADMIN_ID = "11111111-1111-4111-8111-111111111111";
const MEMBER_ID = "22222222-2222-4222-8222-222222222222";

async function fixture() {
  const db = new PGlite();
  await db.exec(`
    create role anon;
    create role authenticated;
    create schema auth;
    create function auth.uid() returns uuid language sql stable
      as 'select nullif(current_setting(''request.jwt.claim.sub'', true), '''')::uuid';

    create table public.profiles (id uuid primary key, is_admin boolean not null default false);
    create table public.albums (
      id bigint generated by default as identity primary key,
      title text not null,
      artist text not null
    );
    create table public.songs (
      id bigint generated by default as identity primary key,
      title text not null,
      artist text not null,
      album_id bigint references public.albums(id) on delete set null,
      external_source text,
      external_id text,
      created_at timestamptz default now(),
      is_deleted boolean default false,
      canonical_song_id uuid,
      track_position integer,
      canonical_song_key text
    );
    create unique index songs_external_identity on public.songs(external_source, external_id)
      where external_source is not null and external_id is not null;
    create unique index songs_album_title on public.songs(album_id, lower(title));
    create table public.song_ratings (
      id bigint generated by default as identity primary key,
      user_id uuid not null,
      song_id bigint references public.songs(id) on delete cascade,
      rating numeric not null
    );

    insert into profiles(id,is_admin) values
      ('${ADMIN_ID}',true),
      ('${MEMBER_ID}',false);
    insert into albums(title,artist) values
      ('The Great Escape','Blur'),
      ('Parklife','Blur');
    insert into songs(title,artist,album_id,external_source,external_id,track_position) values
      ('Stereotypes','Blur',1,'musicbrainz','recording-1',1),
      ('Bonus Track','Blur',1,'musicbrainz','recording-2',2),
      ('Girls & Boys','Blur',2,'musicbrainz','recording-3',1);
    insert into song_ratings(user_id,song_id,rating) values ('${MEMBER_ID}',2,8);

    grant usage on schema public, auth to authenticated;
    grant select on public.profiles to authenticated;
    grant select, update on public.albums to authenticated;
    grant select, insert, update on public.songs to authenticated;
    grant usage, select on sequence public.songs_id_seq to authenticated;
  `);
  await db.exec(migration);
  return db;
}

async function asUser(db, userId, sql, params = []) {
  await db.exec(`set role authenticated; set "request.jwt.claim.sub" = '${userId}'`);
  try {
    return await db.query(sql, params);
  } finally {
    await db.exec('reset role; reset "request.jwt.claim.sub"');
  }
}

test("admin can atomically edit, add, remove and order an album listing", async () => {
  const db = await fixture();
  try {
    const listing = [
      { id: 1, position: 2, title: "Stereotypes (Album Version)", artist: "Blur" },
      { id: null, position: 1, title: "Country House", artist: "Blur" }
    ];
    const result = await asUser(
      db,
      ADMIN_ID,
      "select id,title,track_position from admin_update_album_track_listing($1,$2::jsonb)",
      [1, JSON.stringify(listing)]
    );
    assert.deepEqual(result.rows.map((row) => [row.title, row.track_position]), [
      ["Country House", 1],
      ["Stereotypes (Album Version)", 2]
    ]);

    const detached = await db.query("select album_id,track_position,external_source,external_id from songs where id=2");
    assert.deepEqual(detached.rows[0], {
      album_id: null,
      track_position: null,
      external_source: "musicbrainz",
      external_id: "recording-2"
    });
    assert.equal((await db.query("select count(*)::int count from song_ratings where song_id=2")).rows[0].count, 1);
  } finally {
    await db.close();
  }
});

test("non-admin callers are rejected before any track changes", async () => {
  const db = await fixture();
  try {
    await assert.rejects(
      asUser(
        db,
        MEMBER_ID,
        "select * from admin_update_album_track_listing($1,$2::jsonb)",
        [1, JSON.stringify([{ id: 1, position: 1, title: "Changed", artist: "Blur" }])]
      ),
      /Admin access required/
    );
    assert.equal((await db.query("select title from songs where id=1")).rows[0].title, "Stereotypes");
  } finally {
    await db.close();
  }
});

test("a foreign track or invalid complete set rolls back without detaching existing tracks", async () => {
  const db = await fixture();
  try {
    await assert.rejects(
      asUser(
        db,
        ADMIN_ID,
        "select * from admin_update_album_track_listing($1,$2::jsonb)",
        [1, JSON.stringify([{ id: 3, position: 1, title: "Girls & Boys", artist: "Blur" }])]
      ),
      /Every existing track must belong to the selected album/
    );
    const tracks = await db.query("select id,album_id,track_position,title from songs order by id");
    assert.deepEqual(tracks.rows.map((row) => [row.id, row.album_id, row.track_position, row.title]), [
      [1, 1, 1, "Stereotypes"],
      [2, 1, 2, "Bonus Track"],
      [3, 2, 1, "Girls & Boys"]
    ]);
    assert.equal((await db.query("select count(*)::int count from song_ratings where song_id=2")).rows[0].count, 1);
  } finally {
    await db.close();
  }
});
