import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { PGlite } from "@electric-sql/pglite";

const migration = await readFile(
  new URL("../migrations/20260926120000_admin_catalogue_v1.sql", import.meta.url),
  "utf8"
);
const ADMIN_ID = "11111111-1111-4111-8111-111111111111";
const MEMBER_ID = "22222222-2222-4222-8222-222222222222";
const RELEASE_ID = "33333333-3333-4333-8333-333333333333";
const GROUP_ID = "44444444-4444-4444-8444-444444444444";
const RECORDING_ID = "55555555-5555-4555-8555-555555555555";

async function fixture() {
  const db = new PGlite();
  await db.exec(`
    create role anon;
    create role authenticated;
    create role service_role;
    create schema auth;
    create function auth.uid() returns uuid language sql stable
      as 'select nullif(current_setting(''request.jwt.claim.sub'', true), '''')::uuid';
    create table public.profiles (id uuid primary key, is_admin boolean not null default false);
    create table public.albums (
      id bigint generated by default as identity primary key,
      title text not null, artist text not null, created_at timestamptz default now(),
      external_source text, external_id text, cover_art_url text, release_date date,
      custom_cover text, is_deleted boolean default false,
      musicbrainz_release_group_id text, musicbrainz_release_id text,
      original_release_date date, canonical_release_date date,
      canonical_release_country text, catalogue_selection_version integer
    );
    create unique index albums_external_source_external_id_unique on public.albums(external_source,external_id);
    create unique index albums_title_artist_unique on public.albums(title,artist);
    create unique index albums_musicbrainz_release_group_unique on public.albums(musicbrainz_release_group_id)
      where musicbrainz_release_group_id is not null and is_deleted is not true;
    create table public.songs (
      id bigint generated by default as identity primary key,
      title text not null, artist text not null, album_id bigint references public.albums(id) on delete set null,
      external_source text, external_id text, created_at timestamptz default now(),
      is_deleted boolean default false, canonical_song_id uuid, track_position integer, canonical_song_key text
    );
    create unique index songs_external_source_external_id_unique on public.songs(external_source,external_id);
    create unique index songs_unique_track on public.songs(album_id,lower(title));
    create table public.tracked_artists(id bigint generated by default as identity primary key, artist_name text unique);
    create function public.sync_tracked_artist_from_album() returns trigger language plpgsql as $$
      begin insert into public.tracked_artists(artist_name) values(new.artist) on conflict do nothing; return new; end $$;
    create trigger trg_sync_tracked_artist_from_album after insert on public.albums
      for each row execute function public.sync_tracked_artist_from_album();
    create table public.catalogue_worker_state(
      singleton boolean primary key default true,
      next_musicbrainz_at timestamptz,
      constraint singleton_true check(singleton)
    );
    insert into profiles(id,is_admin) values ('${ADMIN_ID}',true),('${MEMBER_ID}',false);
    grant usage on schema public,auth to anon,authenticated,service_role;
    grant select on public.profiles to authenticated;
    grant select,insert,update,delete on public.albums,public.songs to authenticated;
    grant usage,select on sequence public.albums_id_seq,public.songs_id_seq to authenticated;
    grant all on public.catalogue_worker_state to service_role;
    create policy "Logged in users can insert albums" on public.albums for insert to authenticated with check(auth.uid() is not null);
    create policy "Logged in users can insert songs" on public.songs for insert to authenticated with check(auth.uid() is not null);
    alter table public.albums enable row level security;
    alter table public.songs enable row level security;
    create policy "read albums" on public.albums for select using(true);
    create policy "read songs" on public.songs for select using(true);
    create policy "Admins can do anything on albums" on public.albums to authenticated
      using(exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_admin))
      with check(exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_admin));
    create policy "Admins can do anything on songs" on public.songs to authenticated
      using(exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_admin))
      with check(exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_admin));
  `);
  await db.exec(migration);
  return db;
}

const album = {
  title: "First Album", artist: "The Example",
  musicbrainz_release_id: RELEASE_ID,
  musicbrainz_release_group_id: GROUP_ID,
  cover_art_url: `https://coverartarchive.org/release-group/${GROUP_ID}/front-250`,
  uk_release_date: "1984-02-20", original_release_date: "1984-02-20",
  canonical_release_date: "1984-02-20", canonical_release_country: "GB"
};
const tracks = [{ position: 1, title: "Opening Track", artist: "The Example", musicbrainz_recording_id: RECORDING_ID }];

async function asUser(db, userId, sql, params = []) {
  await db.exec(`set role authenticated; set "request.jwt.claim.sub"='${userId}'`);
  try { return await db.query(sql, params); }
  finally { await db.exec('reset role; reset "request.jwt.claim.sub"'); }
}

async function add(db, userId = ADMIN_ID, requestedAlbum = album, requestedTracks = tracks) {
  return asUser(db, userId,
    "select admin_add_catalogue_album($1::jsonb,$2::jsonb) result",
    [JSON.stringify(requestedAlbum), JSON.stringify(requestedTracks)]);
}

test("migration closes member inserts and removes automatic tracked-artist creation", async () => {
  const db = await fixture();
  try {
    const policies = await db.query(`select policyname from pg_policies where schemaname='public'
      and policyname in ('Logged in users can insert albums','Logged in users can insert songs')`);
    assert.equal(policies.rows.length, 0);
    const trigger = await db.query("select 1 from pg_trigger where tgname='trg_sync_tracked_artist_from_album'");
    assert.equal(trigger.rows.length, 0);
    await assert.rejects(
      asUser(db, MEMBER_ID, "insert into albums(title,artist) values('No','Member')"),
      /row-level security|policy/i
    );
  } finally { await db.close(); }
});

test("admin RPC atomically adds canonical album provenance and tracks", async () => {
  const db = await fixture();
  try {
    const response = (await add(db)).rows[0].result;
    assert.equal(response.status, "added");
    assert.equal(response.track_count, 1);
    const saved = (await db.query("select * from albums")).rows[0];
    assert.equal(saved.musicbrainz_release_group_id, GROUP_ID);
    assert.equal(saved.release_date.toISOString().slice(0,10), "1984-02-20");
    assert.equal(saved.canonical_release_country, "GB");
    const savedTrack = (await db.query("select * from songs")).rows[0];
    assert.equal(savedTrack.album_id, saved.id);
    assert.equal(savedTrack.external_id, RECORDING_ID);
    assert.equal((await db.query("select count(*)::int n from tracked_artists")).rows[0].n, 0);
  } finally { await db.close(); }
});

test("non-admin RPC calls fail before any catalogue write", async () => {
  const db = await fixture();
  try {
    await assert.rejects(add(db, MEMBER_ID), /Admin access required/);
    assert.equal((await db.query("select count(*)::int n from albums")).rows[0].n, 0);
    assert.equal((await db.query("select count(*)::int n from songs")).rows[0].n, 0);
  } finally { await db.close(); }
});

test("duplicate release groups return Already exists without adding tracks", async () => {
  const db = await fixture();
  try {
    assert.equal((await add(db)).rows[0].result.status, "added");
    const duplicate = (await add(db, ADMIN_ID, { ...album, musicbrainz_release_id: "77777777-7777-4777-8777-777777777777" }, [
      { ...tracks[0], musicbrainz_recording_id: "88888888-8888-4888-8888-888888888888" }
    ])).rows[0].result;
    assert.equal(duplicate.status, "already_exists");
    assert.equal((await db.query("select count(*)::int n from albums")).rows[0].n, 1);
    assert.equal((await db.query("select count(*)::int n from songs")).rows[0].n, 1);
  } finally { await db.close(); }
});

test("track conflicts are reported before insertion", async () => {
  const db = await fixture();
  try {
    await db.exec(`insert into albums(title,artist) values('Other','The Example');
      insert into songs(title,artist,album_id,external_source,external_id,track_position)
      values('Opening Track','The Example',1,'musicbrainz','${RECORDING_ID}',1)`);
    const response = (await add(db, ADMIN_ID, { ...album, title: "New Album" })).rows[0].result;
    assert.equal(response.status, "needs_correction");
    assert.equal(response.reason, "recording_already_belongs_to_another_catalogue_row");
    assert.equal((await db.query("select count(*)::int n from albums")).rows[0].n, 1);
  } finally { await db.close(); }
});

test("an invalid track rolls back the whole album", async () => {
  const db = await fixture();
  try {
    await assert.rejects(add(db, ADMIN_ID, album, [{ ...tracks[0], musicbrainz_recording_id: "not-a-uuid" }]),
      /Every track requires/);
    assert.equal((await db.query("select count(*)::int n from albums")).rows[0].n, 0);
    assert.equal((await db.query("select count(*)::int n from songs")).rows[0].n, 0);
  } finally { await db.close(); }
});

test("MusicBrainz slots are shared without touching importer queue data", async () => {
  const db = await fixture();
  try {
    await db.exec("set role service_role");
    const first = (await db.query("select admin_catalogue_musicbrainz_slot() wait_ms")).rows[0].wait_ms;
    const second = (await db.query("select admin_catalogue_musicbrainz_slot() wait_ms")).rows[0].wait_ms;
    await db.exec("reset role");
    assert.equal(first, 0);
    assert.ok(second > 0);
  } finally { await db.close(); }
});
