import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
const require = createRequire(process.env.CATALOGUE_TEST_PACKAGE || import.meta.url);
const { PGlite } = require("@electric-sql/pglite");

export async function database() {
  const db = new PGlite();
  const baseline = readFileSync(new URL("../exports/production_schema.sql", import.meta.url), "utf8");
  const tables = ["artist_import_queue", "albums", "artist_catalog", "artist_release_group_debug"];
  for (const name of tables) {
    const start = baseline.indexOf(`CREATE TABLE IF NOT EXISTS "public"."${name}"`);
    await db.exec(baseline.slice(start, baseline.indexOf("\n);", start) + 3));
  }
  await db.exec(`
    create role anon; create role authenticated; create role service_role bypassrls;
    alter table artist_import_queue add primary key(id);
    alter table artist_import_queue alter id add generated by default as identity;
    alter table albums add primary key(id);
    alter table albums alter id add generated by default as identity;
    create unique index album_external on albums(external_source,external_id);
    create unique index album_title on albums(title,artist);
    alter table artist_catalog add primary key(artist_name);
    create function claim_next_artist_import() returns artist_import_queue language sql as 'select null::artist_import_queue';
    grant usage on schema public to service_role,anon,authenticated;
    grant all on all tables in schema public to service_role;
    grant all on all sequences in schema public to service_role;
  `);
  const migration = readFileSync(new URL("../migrations/20260910151106_catalogue_worker_safeguards.sql", import.meta.url), "utf8");
  await db.exec(migration);
  const shadowMigration = readFileSync(new URL("../migrations/20260911143000_catalogue_shadow_selection.sql", import.meta.url), "utf8");
  await db.exec(shadowMigration);
  const acquisitionMigration = readFileSync(new URL("../migrations/20260911211500_catalogue_worker_idempotent_acquire.sql", import.meta.url), "utf8");
  await db.exec(acquisitionMigration);
  const coordinationMigration = readFileSync(new URL("../migrations/20260912083000_catalogue_worker_idempotent_coordination.sql", import.meta.url), "utf8");
  await db.exec(coordinationMigration);
  const reviewMigration = readFileSync(new URL("../migrations/20260912114500_catalogue_qualification_review_queue.sql", import.meta.url), "utf8");
  await db.exec(reviewMigration);
  const creditMigration = readFileSync(new URL("../migrations/20260914074613_qualification_v2_credit_provenance.sql", import.meta.url), "utf8");
  await db.exec(creditMigration);
  const recoveryMigration = readFileSync(new URL("../migrations/20260918175815_catalogue_recovery_observability.sql", import.meta.url), "utf8");
  await db.exec(recoveryMigration);
  return db;
}

export async function rpc(db, token, action, jobId = null, data = {}) {
  if ((action === "rate" || action === "cooldown") && !data.request_token) {
    data = { ...data, request_token: crypto.randomUUID() };
  }
  const result = await db.query("select catalogue_worker($1,$2::uuid,$3::bigint,$4::jsonb) result", [action, token, jobId, JSON.stringify(data)]);
  return result.rows[0].result;
}

export function adapter(db) {
  return {
    async rpc(name, args) {
      if (name === "upsert_artist_catalogue_review") {
        try {
          const result = await db.query(`select upsert_artist_catalogue_review(
            $1,$2,$3,$4,$5,$6,$7,$8,$9,$10) result`, [
            args.p_release_group_id,args.p_musicbrainz_artist_id,args.p_artist_name,
            args.p_release_group_title,args.p_release_group_original_date,args.p_review_reason,
            args.p_proposed_release_id,args.p_proposed_release_date,args.p_proposed_release_country,
            args.p_proposed_selection_strategy
          ]);
          return { data: result.rows[0].result, error: null };
        } catch (error) { return { data: null, error: { message: error.message } }; }
      }
      try { return { data: await rpc(db, args.p_token, args.p_action, args.p_job_id, args.p_data), error: null }; }
      catch (error) { return { data: null, error: { message: error.message } }; }
    },
    from(table) {
      if (table === "artist_catalogue_overrides") {
        return { select: async () => ({ data: (await db.query("select * from artist_catalogue_overrides")).rows, error: null }) };
      }
      if (table === "artist_catalogue_shadow_snapshots" || table === "artist_catalogue_shadow_decisions") {
        const conditions = [], values = [];
        const query = { select() { return query; }, eq(key,value) {
          conditions.push(`"${key}" = $${values.push(value)}`); return query;
        }, async then(resolve,reject) { try {
          const result = await db.query(`select * from ${table}${conditions.length ? ` where ${conditions.join(" and ")}` : ""}`,values);
          return resolve({data:result.rows,error:null});
        } catch(error) { return reject(error); } } };
        query.upsert = async row => {
          if (table === "artist_catalogue_shadow_snapshots") {
            await db.query(`insert into artist_catalogue_shadow_snapshots
              (job_id,qualification_version,qualified_release_group_ids,review_release_group_ids,
               legacy_processed_release_group_ids,proposed_next_index,ready,updated_at)
              values($1,$2,$3::jsonb,$4::jsonb,$5::jsonb,$6,$7,$8)
              on conflict(job_id,qualification_version) do update set
                qualified_release_group_ids=excluded.qualified_release_group_ids,
                review_release_group_ids=excluded.review_release_group_ids,
                legacy_processed_release_group_ids=excluded.legacy_processed_release_group_ids,
                proposed_next_index=excluded.proposed_next_index,ready=excluded.ready,updated_at=excluded.updated_at`,
              [row.job_id,row.qualification_version,JSON.stringify(row.qualified_release_group_ids),
               JSON.stringify(row.review_release_group_ids),JSON.stringify(row.legacy_processed_release_group_ids),
               row.proposed_next_index,row.ready,row.updated_at]);
          } else {
            await db.query(`insert into artist_catalogue_shadow_decisions
              (job_id,release_group_id,qualification_version,selection_version,release_group_title,
               original_release_date,qualification,qualification_reason,proposed_release_id,
               proposed_release_date,proposed_release_country,selection_strategy,legacy_release_id,
               legacy_reason,artist_credit,observed_at)
              values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15::jsonb,$16)
              on conflict(job_id,release_group_id,qualification_version,selection_version) do update set
                release_group_title=excluded.release_group_title,original_release_date=excluded.original_release_date,
                qualification=excluded.qualification,qualification_reason=excluded.qualification_reason,
                proposed_release_id=excluded.proposed_release_id,proposed_release_date=excluded.proposed_release_date,
                proposed_release_country=excluded.proposed_release_country,selection_strategy=excluded.selection_strategy,
                legacy_release_id=excluded.legacy_release_id,legacy_reason=excluded.legacy_reason,
                artist_credit=excluded.artist_credit,observed_at=excluded.observed_at`,
              [row.job_id,row.release_group_id,row.qualification_version,row.selection_version,row.release_group_title,
               row.original_release_date,row.qualification,row.qualification_reason,row.proposed_release_id,
               row.proposed_release_date,row.proposed_release_country,row.selection_strategy,row.legacy_release_id,
               row.legacy_reason,JSON.stringify(row.artist_credit || []),row.observed_at]);
          }
          return { data: null, error: null };
        };
        return query;
      }
      if (table !== "albums") throw Error("Only album reads are allowed outside fenced RPCs");
      let conditions = [], values = [], single = false;
      const query = {
        select() { return query; },
        eq(key, value) { conditions.push(`"${key}" = $${values.push(value)}`); return query; },
        ilike(key, value) { conditions.push(`"${key}" ilike $${values.push(value)}`); return query; },
        maybeSingle() { single = true; return query; },
        async then(resolve, reject) {
          try {
            const result = await db.query(`select * from albums where ${conditions.join(" and ")}`, values);
            return resolve({ data: single ? result.rows[0] : result.rows, error: null });
          } catch(error) { return reject(error); }
        }
      };
      return query;
    }
  };
}
