import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { PGlite } from "@electric-sql/pglite";

const migration = await readFile(
  new URL("../migrations/20261004140000_convert_definitely_maybe_audio.sql", import.meta.url),
  "utf8"
);
const correctiveMigration = await readFile(
  new URL("../migrations/20261004150000_fix_definitely_maybe_admin_delete.sql", import.meta.url),
  "utf8"
);

const ADMIN_ID = "076d961e-c330-4cf7-a820-e0b45a8b8cd0";
const BARCS_ID = "a9824c00-1aa0-4bd1-96d4-0c71f84ec5ca";
const MEMBER_ID = "22222222-2222-4222-8222-222222222222";
const RELEASE_ID = "feeedf8d-7bff-43eb-b8d5-c3ac75612f53";
const GROUP_ID = "451dca98-c118-32e1-9244-c47ca9c3c0f9";
const SAD_SONG_ID = "7bdf247f-2582-4339-8c97-55bd18fea1b9";

const sourceTracks = [
  [3,"Rock ’n’ Roll Star","66371e8a-2ccb-47bd-bb83-a50f787e2614","17z8eLCkciVamEqXJS6Ri8"],
  [4,"Shakermaker","9c28c538-3d59-4d0d-89ca-2dfa7812a61c",null],
  [5,"Live Forever","e69f62d5-98e3-4e3f-afd8-e26039e01ad4","5IfBLN9VPPJOwcKmAZhdXe"],
  [6,"Up in the Sky","0062a947-8795-4f91-9b9d-4d03a5039713",null],
  [7,"Columbia","056d8bf5-c566-4407-bb18-9b3cafd8f2f5",null],
  [8,"Supersonic","fc07707b-327e-45d7-b904-9cb961f949e5",null],
  [9,"Bring It On Down","a2ec86d1-165c-4af3-9d7f-12154bc0940b",null],
  [10,"Cigarettes & Alcohol","443854e1-da2e-4393-8ce4-6b8954c85084","3nK2qGHdVAEOuVAmMSWQPW"],
  [11,"Digsy’s Dinner","7ba38242-6c70-4a9d-81c5-f910a0143d45",null],
  [12,"Slide Away","22e1a8e4-ee17-4bd3-83b8-100d4d59ce63",null],
  [13,"Married With Children","500e081a-39a5-4b23-887f-6f184c3ac90a","0oemhAQXaaIHCEARF9JFGg"],
  [14,"Sad Song","3e793c92-d56a-40d6-affe-9966e905b296",null],
  [15,"Rock ’n’ Roll Star (Top of the Pops, September 1994)","f13559d5-85f6-4e30-943c-9a89cbfd2bce",null],
  [16,"Shakermaker (Naked City, June 1994)","9c226e2b-bbb5-4d65-8706-e85dffe1e0f5",null],
  [17,"Live Forever (Glastonbury, June 1994)","26650b5a-0a22-4f47-861c-d8424538913d",null],
  [18,"Up in the Sky (Chicago Metro, October 1994)","486262d0-fb44-4c55-9ac1-e0e6a9423781",null],
  [19,"Columbia (Hammersmith Palais, December 1994)","00f8a47b-7866-4336-b353-52215251343a",null],
  [20,"Supersonic (The Word, March 1994)","fb030469-3c2f-4204-a1c5-8c97abbf7118",null],
  [21,"Bring It On Down (Gleneagles, February 1994)","6dac9017-17ad-45c9-97de-efe31951a8c7",null],
  [22,"Cigarettes & Alcohol (Southampton Guildhall, November 1994)","eaceb5f1-eb1a-47ac-b1c0-37e3244e1db8",null],
  [23,"Digsy’s Dinner (Buckley Tivoli, August 1994)","c163aa96-1e39-48f6-a65d-84c1e80500c4",null],
  [24,"Slide Away (New York Wetlands, July 1994)","c57c9ee0-7d92-4813-901c-72df2de31b9b",null],
  [25,"Married With Children (Los Angeles Whiskey a Go Go, September 1994)","5e8e6ba9-6dc5-4e33-bb09-3452a7b77106",null],
  [26,"Sad Song (Later with Jools Holland, December 1994)","77491194-9aa2-44c1-a531-30ec86ac2ba0",null]
];

const targetTracks = [
  [1,"Rock ’n’ Roll Star","25952523-6d7d-4c26-bf1f-52111006a6a5"],
  [2,"Shakermaker","bcb2841c-a2ef-43d6-89ef-d636ea0eee48"],
  [3,"Live Forever","43cf19be-cdcf-48a9-beea-4d0b56887317"],
  [4,"Up in the Sky","87e571cc-29d3-48b5-9746-3b74ae082680"],
  [5,"Columbia","691e5a27-878d-4bc1-941a-111142c48094"],
  [6,"Sad Song",SAD_SONG_ID],
  [7,"Supersonic","901e8dd7-3859-4243-a999-c7bc359c9984"],
  [8,"Bring It On Down","96986d93-6822-4e30-b743-2d693f9f8297"],
  [9,"Cigarettes & Alcohol","068b3632-4b4c-4e0a-a18c-a2a3cb8c940e"],
  [10,"Digsy’s Dinner","d4925377-59e3-45d0-ba95-73378bde72eb"],
  [11,"Slide Away","24564eb6-fc94-491b-87a2-a2349dfa05db"],
  [12,"Married With Children","840ee517-3bf8-4816-b825-40b17a88b382"]
];

const songRatings = [
  [5,3,9],[22,4,8],[2,5,10],[139,6,8],[140,7,8],[3,8,9],
  [141,9,7],[4,10,9],[143,11,8],[144,12,8],[146,13,9],[147,14,9]
];

async function fixture({ applyCorrection = true } = {}) {
  const db = new PGlite();
  await db.exec(`
    create role anon; create role authenticated; create role service_role;
    create schema auth;
    create function auth.uid() returns uuid language sql stable
      as 'select nullif(current_setting(''request.jwt.claim.sub'', true), '''')::uuid';
    create table public.profiles(id uuid primary key,is_admin boolean not null default false);
    create table public.albums(
      id bigint generated by default as identity primary key,title text not null,artist text not null,
      external_source text,external_id text,is_deleted boolean default false,
      musicbrainz_release_id text,musicbrainz_release_group_id text,cover_art_url text,
      release_date date,original_release_date date,canonical_release_date date,
      canonical_release_country text,catalogue_selection_version integer
    );
    create table public.songs(
      id bigint generated by default as identity primary key,title text not null,artist text not null,
      album_id bigint references public.albums(id),external_source text,external_id text,
      is_deleted boolean default false,spotify_track_id text,track_position integer
    );
    create unique index songs_album_recording on public.songs(album_id,external_source,external_id);
    create unique index songs_album_position on public.songs(album_id,track_position);
    create table public.song_ratings(
      id bigint primary key,user_id uuid not null,song_id bigint references public.songs(id) on delete cascade,
      rating numeric not null,created_at timestamptz default now(),unique(user_id,song_id)
    );
    create table public.ratings(
      id bigint primary key,user_id uuid not null,album_id bigint references public.albums(id),
      rating numeric not null,created_at timestamptz default now(),unique(user_id,album_id)
    );
    create table public.album_reviews(id uuid primary key,user_id uuid not null,album_id bigint not null);
    create table public.album_review_comments(
      id uuid primary key,review_id uuid references public.album_reviews(id),user_id uuid not null,comment_text text
    );
    create table public.album_review_likes(
      review_id uuid references public.album_reviews(id),user_id uuid not null,primary key(review_id,user_id)
    );
    create table public.catalogue_release_group_exclusions(
      musicbrainz_release_group_id text primary key,artist text not null,title text not null
    );
    insert into public.profiles values
      ('${ADMIN_ID}',true),('${BARCS_ID}',false),('${MEMBER_ID}',false);
    insert into public.albums(id,title,artist,external_source,external_id,is_deleted)
      values(6,'Definitely Maybe','Oasis','musicbrainz','727e4a55-c407-458e-9dbc-ee6dbe204617',false);
    grant usage on schema public,auth to authenticated,service_role;
    grant select on public.profiles to authenticated;
    grant select,insert,update,delete on all tables in schema public to authenticated;
    grant usage,select on sequence public.songs_id_seq to authenticated;
    alter table public.ratings enable row level security;
    create policy "Public read ratings" on public.ratings for select using (true);
    create policy "Users can delete own album ratings" on public.ratings for delete
      to authenticated using (user_id = auth.uid());
    alter table public.song_ratings enable row level security;
    create policy "Public read song ratings" on public.song_ratings for select using (true);
    create policy "Users can delete own song ratings" on public.song_ratings for delete
      to authenticated using (user_id = auth.uid());
  `);
  for (const [id,title,recording,spotify] of sourceTracks) {
    await db.query(`insert into songs(id,title,artist,album_id,external_source,external_id,is_deleted,spotify_track_id)
      values($1,$2,'Oasis',6,'musicbrainz',$3,false,$4)`, [id,title,recording,spotify]);
  }
  await db.query("select setval('public.songs_id_seq',1000,true)");
  for (const [id,songId,rating] of songRatings) {
    await db.query("insert into song_ratings(id,user_id,song_id,rating) values($1,$2,$3,$4)",
      [id,ADMIN_ID,songId,rating]);
  }
  await db.query("insert into ratings(id,user_id,album_id,rating) values(14,$1,6,10),(60,$2,6,5)",
    [ADMIN_ID,BARCS_ID]);
  await db.exec(migration);
  if (applyCorrection) await db.exec(correctiveMigration);
  return db;
}

async function asUser(db, userId, execute) {
  await db.exec(`set role authenticated; set "request.jwt.claim.sub"='${userId}'`);
  try {
    return await db.query("select public.admin_convert_definitely_maybe($1) result", [execute]);
  } finally {
    await db.exec('reset role; reset "request.jwt.claim.sub"');
  }
}

test("guarded conversion previews then atomically replaces the DVD catalogue with twelve audio tracks", async () => {
  const db = await fixture();
  try {
    const preview = (await asUser(db, ADMIN_ID, false)).rows[0].result;
    assert.deepEqual(preview, {
      status: "preview", album_id: 6, source_track_count: 24, target_track_count: 12,
      album_rating_deletions: 2, song_rating_deletions: 12
    });
    assert.equal((await db.query("select count(*)::int n from songs where album_id=6")).rows[0].n, 24);

    const result = (await asUser(db, ADMIN_ID, true)).rows[0].result;
    assert.equal(result.status, "converted");
    assert.equal(result.sad_song_recording_id, SAD_SONG_ID);
    const album = (await db.query(`select id,external_id,musicbrainz_release_id,musicbrainz_release_group_id,
      release_date,original_release_date,canonical_release_date,canonical_release_country,catalogue_selection_version
      from albums where id=6`)).rows[0];
    assert.equal(Number(album.id), 6);
    assert.equal(album.external_id, RELEASE_ID);
    assert.equal(album.musicbrainz_release_id, RELEASE_ID);
    assert.equal(album.musicbrainz_release_group_id, GROUP_ID);
    assert.equal(album.release_date.toISOString().slice(0,10), "1994-08-30");
    assert.equal(album.original_release_date.toISOString().slice(0,10), "1994-08-30");
    assert.equal(album.canonical_release_date.toISOString().slice(0,10), "1994-08-30");
    assert.equal(album.canonical_release_country, "GB");
    assert.equal(album.catalogue_selection_version, 1);

    const saved = (await db.query(`select track_position,title,external_id,spotify_track_id
      from songs where album_id=6 order by track_position`)).rows;
    assert.deepEqual(saved.map(row => [row.track_position,row.title,row.external_id]), targetTracks);
    assert.ok(saved.every(row => row.spotify_track_id === null));
    assert.equal((await db.query("select count(*)::int n from ratings where album_id=6")).rows[0].n, 0);
    assert.equal((await db.query("select count(*)::int n from song_ratings")).rows[0].n, 0);
    assert.equal((await db.query("select count(*)::int n from catalogue_release_group_exclusions")).rows[0].n, 0);
  } finally { await db.close(); }
});

test("the deployed invoker function reproduces the cross-user album-rating RLS failure", async () => {
  const db = await fixture({ applyCorrection: false });
  try {
    const preview = (await asUser(db, ADMIN_ID, false)).rows[0].result;
    assert.equal(preview.album_rating_deletions, 2);
    await assert.rejects(asUser(db, ADMIN_ID, true), /Expected album ratings were not deleted/);
    assert.equal((await db.query("select count(*)::int n from ratings where album_id=6")).rows[0].n, 2);
    assert.equal((await db.query("select count(*)::int n from song_ratings")).rows[0].n, 12);
    assert.equal((await db.query("select count(*)::int n from songs where album_id=6")).rows[0].n, 24);
  } finally { await db.close(); }
});

test("changed source state or an unexpected dependency aborts without partial mutation", async () => {
  const db = await fixture();
  try {
    await db.query("insert into album_reviews values($1,$2,6)",
      ["33333333-3333-4333-8333-333333333333", MEMBER_ID]);
    await assert.rejects(asUser(db, ADMIN_ID, true), /user data has changed/);
    assert.equal((await db.query("select external_id from albums where id=6")).rows[0].external_id,
      "727e4a55-c407-458e-9dbc-ee6dbe204617");
    assert.equal((await db.query("select count(*)::int n from songs where album_id=6")).rows[0].n, 24);
    assert.equal((await db.query("select count(*)::int n from ratings where album_id=6")).rows[0].n, 2);
    assert.equal((await db.query("select count(*)::int n from song_ratings")).rows[0].n, 12);
  } finally { await db.close(); }
});

test("ordinary users cannot invoke the one-off conversion", async () => {
  const db = await fixture();
  try {
    await assert.rejects(asUser(db, MEMBER_ID, true), /Admin access required/);
    assert.equal((await db.query("select count(*)::int n from songs where album_id=6")).rows[0].n, 24);
  } finally { await db.close(); }
});
