import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { test } from "node:test";
import { PGlite } from "@electric-sql/pglite";

const migrationUrl = new URL(
  "../migrations/20260920074353_secure_tracked_artist_album_trigger.sql",
  import.meta.url
);

test("album trigger can sync tracked artists without exposing a privileged RPC", async () => {
  const db = new PGlite();
  try {
    await db.exec(`
      create role anon;
      create role authenticated;

      create table public.albums (
        id bigint generated by default as identity primary key,
        title text not null,
        artist text not null
      );
      create table public.tracked_artists (
        id bigint generated by default as identity primary key,
        artist_name text not null unique
      );
      alter table public.tracked_artists enable row level security;

      create function public.sync_tracked_artist_from_album()
      returns trigger
      language plpgsql
      as $function$
      begin
        if new.artist is not null and trim(new.artist) <> '' then
          insert into public.tracked_artists (artist_name)
          values (trim(new.artist))
          on conflict (artist_name) do nothing;
        end if;
        return new;
      end;
      $function$;

      create trigger trg_sync_tracked_artist_from_album
      after insert on public.albums
      for each row execute function public.sync_tracked_artist_from_album();

      grant usage on schema public to anon, authenticated;
      grant insert on table public.albums to authenticated;
      grant usage, select on sequence public.albums_id_seq to authenticated;
      alter table public.albums enable row level security;
      create policy authenticated_album_insert on public.albums
        for insert to authenticated with check (true);

      revoke all on table public.tracked_artists from anon, authenticated;
      revoke all on sequence public.tracked_artists_id_seq from anon, authenticated;
    `);

    await db.exec(await readFile(migrationUrl, "utf8"));

    const functionSecurity = await db.query(`
      select
        p.prosecdef as security_definer,
        p.proconfig as settings,
        has_function_privilege('anon', p.oid, 'execute') as anon_execute,
        has_function_privilege('authenticated', p.oid, 'execute') as authenticated_execute
      from pg_proc p
      join pg_namespace n on n.oid = p.pronamespace
      where n.nspname = 'public'
        and p.proname = 'sync_tracked_artist_from_album'
    `);
    assert.deepEqual(functionSecurity.rows[0], {
      security_definer: true,
      settings: ["search_path=pg_catalog"],
      anon_execute: false,
      authenticated_execute: false
    });

    await db.exec(`
      set role authenticated;
      insert into public.albums (title, artist) values ('Pink Moon', 'Nick Drake');
      insert into public.albums (title, artist) values ('Pink Moon Again', 'Nick Drake');
      reset role;
    `);
    const tracked = await db.query("select artist_name from public.tracked_artists");
    assert.deepEqual(tracked.rows, [{ artist_name: "Nick Drake" }]);

    await db.exec("set role authenticated");
    await assert.rejects(
      db.exec("insert into public.tracked_artists (artist_name) values ('Direct write')"),
      /permission denied/
    );
    await assert.rejects(
      db.query("select public.sync_tracked_artist_from_album()"),
      /permission denied/
    );
    await db.exec("reset role");
  } finally {
    await db.close();
  }
});
